### ISSUE TITLE
Redo Database Connection to Work with Spring

### ISSUE THREAD

**Issue by meistejw** [RoseContactTracer/contact-tracer-application#11]
I didn't realize that Spring had its own way of handling databases when I initially connected the database.

**Comment by MCoriale** [comment]
There is a more Spring-like approach, it looks like you're handling the ORM stuff yourself but there are ways to do it with annotations. We may have to all get together to discuss pros and cons.

**Comment by MCoriale** [comment]
https://docs.spring.io/spring-data/data-commons/docs/1.6.1.RELEASE/reference/html/repositories.html
